# ============================================================
#  DeepSeek Harness One-Click Launcher generator
#  Generates in THIS script's folder:
#    start-dsh.bat        double-click to start DeepSeek Harness
#    DeepSeekHarness.exe  same, as an .exe wrapper
#  Usage: right-click this file -> "Run with PowerShell"
#  Requirements: Windows (PowerShell is built in). No Node needed
#  to GENERATE; the launcher itself auto-installs dsh on first run.
# ============================================================
$dir = if ($PSScriptRoot) { $PSScriptRoot } else { (Get-Location).Path }

# DeepSeekHarness.exe (launcher shell that opens start-dsh.bat)
$exeB64 = 'TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAOyhfmoAAAAAAAAAAOAAAgELAQsAAAYAAAAIAAAAAAAA7iQAAAAgAAAAQAAAAABAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAIAQIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAKAkAABLAAAAAEAAAPgEAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAA9AQAAAAgAAAABgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAPgEAAAAQAAAAAYAAAAIAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAADgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAADQJAAAAAAAAEgAAAACAAUAxCAAANwDAAABAAAAAQAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABswAgBWAAAAAQAAEQAoBAAAChaaKAUAAAoKBnIBAABwKAYAAAoLBygHAAAKDQktAisvAHMIAAAKDAgHbwkAAAoACAZvCgAACgAIF28LAAAKAAgoDAAACiYA3gUmAADeAAAqAAABEAAAAAAmAClPAAUBAAABQlNKQgEAAQAAAAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAARAEAACN+AACwAQAAiAEAACNTdHJpbmdzAAAAADgDAAAgAAAAI1VTAFgDAAAQAAAAI0dVSUQAAABoAwAAdAAAACNCbG9iAAAAAAAAAAIAAAFHFAIACQAAAAD6JTMAFgAAAQAAAAkAAAACAAAAAQAAAAwAAAADAAAAAQAAAAEAAAACAAAAAAAKAAEAAAAAAAYANwAwAAYAYwBDAAYAiQBDAAYAtwAwAAYAygAwAAYA8wDpAAYAEQHpAAoAMAEdAQoAdwEdAQAAAAABAAAAAAABAAEAgAEQAB4AAAAFAAEAAQBQIAAAAACRAD4ACgABABEAgwAOABkAgwATACEAgwATACkA1gAcADEA+AAhADEACQEmADkAFgEsAEEAgwATAEEAQQExAEEATgExAEEAYwE2AEkAfwE7ACAAGwAXAC4ACwBKAC4AEwBTAEIABIAAAAAAAAAAAAAAAAAAAAAApwAAAAQAAAAAAAAAAAAAAAEAJwAAAAAABAAAAAAAAAAAAAAAAQAwAAAAAAAAAAAAADxNb2R1bGU+AERlZXBTZWVrSGFybmVzcy5leGUATGF1bmNoZXIAbXNjb3JsaWIAU3lzdGVtAE9iamVjdABNYWluAFN5c3RlbS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQAuY3RvcgBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBEZWVwU2Vla0hhcm5lc3MAU1RBVGhyZWFkQXR0cmlidXRlAEVudmlyb25tZW50AEdldENvbW1hbmRMaW5lQXJncwBTeXN0ZW0uSU8AUGF0aABHZXREaXJlY3RvcnlOYW1lAENvbWJpbmUARmlsZQBFeGlzdHMAU3lzdGVtLkRpYWdub3N0aWNzAFByb2Nlc3NTdGFydEluZm8Ac2V0X0ZpbGVOYW1lAHNldF9Xb3JraW5nRGlyZWN0b3J5AHNldF9Vc2VTaGVsbEV4ZWN1dGUAUHJvY2VzcwBTdGFydAAAAAAAG3MAdABhAHIAdAAtAGQAcwBoAC4AYgBhAHQAAQAAAOJ0u91DRzRLud+YI6VMPCUACLd6XFYZNOCJAwAAAQQgAQEIAyAAAQQBAAAABAAAHQ4EAAEODgUAAg4ODgQAAQIOBCABAQ4EIAEBAgYAARIlEiEHBwQODhIhAggBAAgAAAAAAB4BAAEAVAIWV3JhcE5vbkV4Y2VwdGlvblRocm93cwEAAMgkAAAAAAAAAAAAAN4kAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQJAAAAAAAAAAAX0NvckV4ZU1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAEAAAACAAAIAYAAAAOAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAUAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAaAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAkAAAAKBAAABkAgAAAAAAAAAAAAAIQwAA6gEAAAAAAAAAAAAAZAI0AAAAVgBTAF8AVgBFAFIAUwBJAE8ATgBfAEkATgBGAE8AAAAAAL0E7/4AAAEAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAABAAAAAEAAAAAAAAAAAAAAAAAAABEAAAAAQBWAGEAcgBGAGkAbABlAEkAbgBmAG8AAAAAACQABAAAAFQAcgBhAG4AcwBsAGEAdABpAG8AbgAAAAAAAACwBMQBAAABAFMAdAByAGkAbgBnAEYAaQBsAGUASQBuAGYAbwAAAKABAAABADAAMAAwADAAMAA0AGIAMAAAACwAAgABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAAAgAAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAAAAAwAC4AMAAuADAALgAwAAAASAAUAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABEAGUAZQBwAFMAZQBlAGsASABhAHIAbgBlAHMAcwAuAGUAeABlAAAAKAACAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAIAAAAFAAFAABAE8AcgBpAGcAaQBuAGEAbABGAGkAbABlAG4AYQBtAGUAAABEAGUAZQBwAFMAZQBlAGsASABhAHIAbgBlAHMAcwAuAGUAeABlAAAANAAIAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMAAuADAALgAwAC4AMAAAADgACAABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMAaQBvAG4AAAAwAC4AMAAuADAALgAwAAAAAAAAAO+7vzw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9IlVURi04IiBzdGFuZGFsb25lPSJ5ZXMiPz4NCjxhc3NlbWJseSB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjEiIG1hbmlmZXN0VmVyc2lvbj0iMS4wIj4NCiAgPGFzc2VtYmx5SWRlbnRpdHkgdmVyc2lvbj0iMS4wLjAuMCIgbmFtZT0iTXlBcHBsaWNhdGlvbi5hcHAiLz4NCiAgPHRydXN0SW5mbyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjIiPg0KICAgIDxzZWN1cml0eT4NCiAgICAgIDxyZXF1ZXN0ZWRQcml2aWxlZ2VzIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52MyI+DQogICAgICAgIDxyZXF1ZXN0ZWRFeGVjdXRpb25MZXZlbCBsZXZlbD0iYXNJbnZva2VyIiB1aUFjY2Vzcz0iZmFsc2UiLz4NCiAgICAgIDwvcmVxdWVzdGVkUHJpdmlsZWdlcz4NCiAgICA8L3NlY3VyaXR5Pg0KICA8L3RydXN0SW5mbz4NCjwvYXNzZW1ibHk+DQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAADAAAAPA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=='

$lines = @(
  '@echo off',
  'setlocal',
  'title DeepSeek Harness',
  'cd /d "%~dp0"',
  '',
  'rem create DeepSeekHarness.exe on first run (PowerShell ships with every Windows)',
  'if exist "DeepSeekHarness.exe" goto haveexe',
  'powershell -NoProfile -ExecutionPolicy Bypass -Command "[IO.File]::WriteAllBytes(''%~dp0DeepSeekHarness.exe'',[Convert]::FromBase64String(''__B64__''))"',
  ':haveexe',
  '',
  'where npm >nul 2>nul',
  'if errorlevel 1 goto nonpm',
  '',
  'rem auto-install dsh on first run so the launcher works in any fresh folder',
  'if exist "node_modules\@deepseek-ai\dsh" goto havedeps',
  'if not exist package.json echo {}> package.json',
  'echo First run: installing dsh, please wait (network required)...',
  'call npm install --no-audit --no-fund -D @deepseek-ai/dsh',
  'if errorlevel 1 goto npmfail',
  ':havedeps',
  '',
  'echo ============================================',
  'echo   DeepSeek Harness launcher',
  'echo   Keep this window open while using it.',
  'echo   Open the URL printed below in your browser.',
  'echo ============================================',
  'echo.',
  'call npm run dsh',
  'echo.',
  'echo Harness stopped.',
  'pause',
  'exit /b 0',
  '',
  ':nonpm',
  'echo [ERROR] npm not found on PATH. Install Node.js first: https://nodejs.org',
  'pause',
  'exit /b 1',
  '',
  ':npmfail',
  'echo [ERROR] npm install failed. Check your network and retry.',
  'pause',
  'exit /b 1'
)

$bat = ($lines -join "`r`n") + "`r`n"
$bat = $bat.Replace('__B64__', $exeB64)

[IO.File]::WriteAllBytes((Join-Path $dir 'DeepSeekHarness.exe'), [Convert]::FromBase64String($exeB64))
[IO.File]::WriteAllText((Join-Path $dir 'start-dsh.bat'), $bat)

Write-Host 'Done:'
Write-Host '  start-dsh.bat        (double-click to start DeepSeek Harness)'
Write-Host '  DeepSeekHarness.exe  (same, as an exe)'
